const { Countries } = require('../models/countries');
var express = require('express');
var router = express.Router();
var dbase = '';
var body = '';


router.get('/', async  function(req, res) {
    let  query =await Countries.find().sort('name');
        console.log("Fetching Countries...")
        res.send(query)

  });
router.post('/',async(req,res)=>{
    
    let body=[
{"country_id":1,"sortname":"AF","name":"Afghanistan","phoneCode":93    },
{"country_id":2,"sortname":"AL","name":"Albania","phoneCode":355    },
{"country_id":3,"sortname":"DZ","name":"Algeria","phoneCode":213    },
{"country_id":4,"sortname":"AS","name":"American Samoa","phoneCode":1684    },
{"country_id":5,"sortname":"AD","name":"Andorra","phoneCode":376    },
{"country_id":6,"sortname":"AO","name":"Angola","phoneCode":244    },
{"country_id":7,"sortname":"AI","name":"Anguilla","phoneCode":1264    },
{"country_id":8,"sortname":"AQ","name":"Antarctica","phoneCode":0    },
{"country_id":9,"sortname":"AG","name":"Antigua And Barbuda","phoneCode":1268    },
{"country_id":10,"sortname":"AR","name":"Argentina","phoneCode":54    },
{"country_id":11,"sortname":"AM","name":"Armenia","phoneCode":374    },
{"country_id":12,"sortname":"AW","name":"Aruba","phoneCode":297    },
{"country_id":13,"sortname":"AU","name":"Australia","phoneCode":61    },
{"country_id":14,"sortname":"AT","name":"Austria","phoneCode":43    },
{"country_id":15,"sortname":"AZ","name":"Azerbaijan","phoneCode":994    },
{"country_id":16,"sortname":"BS","name":"Bahamas The","phoneCode":1242    },
{"country_id":17,"sortname":"BH","name":"Bahrain","phoneCode":973    },
{"country_id":18,"sortname":"BD","name":"Bangladesh","phoneCode":880    },
{"country_id":19,"sortname":"BB","name":"Barbados","phoneCode":1246    },
{"country_id":20,"sortname":"BY","name":"Belarus","phoneCode":375    },
{"country_id":21,"sortname":"BE","name":"Belgium","phoneCode":32    },
{"country_id":22,"sortname":"BZ","name":"Belize","phoneCode":501    },
{"country_id":23,"sortname":"BJ","name":"Benin","phoneCode":229    },
{"country_id":24,"sortname":"BM","name":"Bermuda","phoneCode":1441    },
{"country_id":25,"sortname":"BT","name":"Bhutan","phoneCode":975    },
{"country_id":26,"sortname":"BO","name":"Bolivia","phoneCode":591    },
{"country_id":27,"sortname":"BA","name":"Bosnia and Herzegovina","phoneCode":387    },
{"country_id":28,"sortname":"BW","name":"Botswana","phoneCode":267    },
{"country_id":29,"sortname":"BV","name":"Bouvet Island","phoneCode":0    },
{"country_id":30,"sortname":"BR","name":"Brazil","phoneCode":55    },
{"country_id":31,"sortname":"IO","name":"British Indian Ocean Territory","phoneCode":246    },
{"country_id":32,"sortname":"BN","name":"Brunei","phoneCode":673    },
{"country_id":33,"sortname":"BG","name":"Bulgaria","phoneCode":359    },
{"country_id":34,"sortname":"BF","name":"Burkina Faso","phoneCode":226    },
{"country_id":35,"sortname":"BI","name":"Burundi","phoneCode":257    },
{"country_id":36,"sortname":"KH","name":"Cambodia","phoneCode":855    },
{"country_id":37,"sortname":"CM","name":"Cameroon","phoneCode":237    },
{"country_id":38,"sortname":"CA","name":"Canada","phoneCode":1    },
{"country_id":39,"sortname":"CV","name":"Cape Verde","phoneCode":238    },
{"country_id":40,"sortname":"KY","name":"Cayman Islands","phoneCode":1345    },
{"country_id":41,"sortname":"CF","name":"Central African Republic","phoneCode":236    },
{"country_id":42,"sortname":"TD","name":"Chad","phoneCode":235    },
{"country_id":43,"sortname":"CL","name":"Chile","phoneCode":56    },
{"country_id":44,"sortname":"CN","name":"China","phoneCode":86    },
{"country_id":45,"sortname":"CX","name":"Christmas Island","phoneCode":61    },
{"country_id":46,"sortname":"CC","name":"Cocos (Keeling) Islands","phoneCode":672    },
{"country_id":47,"sortname":"CO","name":"Colombia","phoneCode":57    },
{"country_id":48,"sortname":"KM","name":"Comoros","phoneCode":269    },
{"country_id":49,"sortname":"CG","name":"Republic Of The Congo","phoneCode":242    },
{"country_id":50,"sortname":"CD","name":"Democratic Republic Of The Congo","phoneCode":242    },
{"country_id":51,"sortname":"CK","name":"Cook Islands","phoneCode":682    },
{"country_id":52,"sortname":"CR","name":"Costa Rica","phoneCode":506    },
{"country_id":53,"sortname":"CI","name":"Cote D''Ivoire (Ivory Coast)","phoneCode":225    },
{"country_id":54,"sortname":"HR","name":"Croatia (Hrvatska)","phoneCode":385    },
{"country_id":55,"sortname":"CU","name":"Cuba","phoneCode":53    },
{"country_id":56,"sortname":"CY","name":"Cyprus","phoneCode":357    },
{"country_id":57,"sortname":"CZ","name":"Czech Republic","phoneCode":420    },
{"country_id":58,"sortname":"DK","name":"Denmark","phoneCode":45    },
{"country_id":59,"sortname":"DJ","name":"Djibouti","phoneCode":253    },
{"country_id":60,"sortname":"DM","name":"Dominica","phoneCode":1767    },
{"country_id":61,"sortname":"DO","name":"Dominican Republic","phoneCode":1809    },
{"country_id":62,"sortname":"TP","name":"East Timor","phoneCode":670    },
{"country_id":63,"sortname":"EC","name":"Ecuador","phoneCode":593    },
{"country_id":64,"sortname":"EG","name":"Egypt","phoneCode":20    },
{"country_id":65,"sortname":"SV","name":"El Salvador","phoneCode":503    },
{"country_id":66,"sortname":"GQ","name":"Equatorial Guinea","phoneCode":240    },
{"country_id":67,"sortname":"ER","name":"Eritrea","phoneCode":291    },
{"country_id":68,"sortname":"EE","name":"Estonia","phoneCode":372    },
{"country_id":69,"sortname":"ET","name":"Ethiopia","phoneCode":251    },
{"country_id":70,"sortname":"XA","name":"External Territories of Australia","phoneCode":61    },
{"country_id":71,"sortname":"FK","name":"Falkland Islands","phoneCode":500    },
{"country_id":72,"sortname":"FO","name":"Faroe Islands","phoneCode":298    },
{"country_id":73,"sortname":"FJ","name":"Fiji Islands","phoneCode":679    },
{"country_id":74,"sortname":"FI","name":"Finland","phoneCode":358    },
{"country_id":75,"sortname":"FR","name":"France","phoneCode":33    },
{"country_id":76,"sortname":"GF","name":"French Guiana","phoneCode":594    },
{"country_id":77,"sortname":"PF","name":"French Polynesia","phoneCode":689    },
{"country_id":78,"sortname":"TF","name":"French Southern Territories","phoneCode":0    },
{"country_id":79,"sortname":"GA","name":"Gabon","phoneCode":241    },
{"country_id":80,"sortname":"GM","name":"Gambia The","phoneCode":220    },
{"country_id":81,"sortname":"GE","name":"Georgia","phoneCode":995    },
{"country_id":82,"sortname":"DE","name":"Germany","phoneCode":49    },
{"country_id":83,"sortname":"GH","name":"Ghana","phoneCode":233    },
{"country_id":84,"sortname":"GI","name":"Gibraltar","phoneCode":350    },
{"country_id":85,"sortname":"GR","name":"Greece","phoneCode":30    },
{"country_id":86,"sortname":"GL","name":"Greenland","phoneCode":299    },
{"country_id":87,"sortname":"GD","name":"Grenada","phoneCode":1473    },
{"country_id":88,"sortname":"GP","name":"Guadeloupe","phoneCode":590    },
{"country_id":89,"sortname":"GU","name":"Guam","phoneCode":1671    },
{"country_id":90,"sortname":"GT","name":"Guatemala","phoneCode":502    },
{"country_id":91,"sortname":"XU","name":"Guernsey and Alderney","phoneCode":44    },
{"country_id":92,"sortname":"GN","name":"Guinea","phoneCode":224    },
{"country_id":93,"sortname":"GW","name":"Guinea-Bissau","phoneCode":245    },
{"country_id":94,"sortname":"GY","name":"Guyana","phoneCode":592    },
{"country_id":95,"sortname":"HT","name":"Haiti","phoneCode":509    },
{"country_id":96,"sortname":"HM","name":"Heard and McDonald Islands","phoneCode":0    },
{"country_id":97,"sortname":"HN","name":"Honduras","phoneCode":504    },
{"country_id":98,"sortname":"HK","name":"Hong Kong S.A.R.","phoneCode":852    },
{"country_id":99,"sortname":"HU","name":"Hungary","phoneCode":36    },
{"country_id":100,"sortname":"IS","name":"Iceland","phoneCode":354    },
{"country_id":101,"sortname":"IN","name":"India","phoneCode":91    },
{"country_id":102,"sortname":"country_id","name":"Indonesia","phoneCode":62    },
{"country_id":103,"sortname":"IR","name":"Iran","phoneCode":98    },
{"country_id":104,"sortname":"IQ","name":"Iraq","phoneCode":964    },
{"country_id":105,"sortname":"IE","name":"Ireland","phoneCode":353    },
{"country_id":106,"sortname":"IL","name":"Israel","phoneCode":972    },
{"country_id":107,"sortname":"IT","name":"Italy","phoneCode":39    },
{"country_id":108,"sortname":"JM","name":"Jamaica","phoneCode":1876    },
{"country_id":109,"sortname":"JP","name":"Japan","phoneCode":81    },
{"country_id":110,"sortname":"XJ","name":"Jersey","phoneCode":44    },
{"country_id":111,"sortname":"JO","name":"Jordan","phoneCode":962    },
{"country_id":112,"sortname":"KZ","name":"Kazakhstan","phoneCode":7    },
{"country_id":113,"sortname":"KE","name":"Kenya","phoneCode":254    },
{"country_id":114,"sortname":"KI","name":"Kiribati","phoneCode":686    },
{"country_id":115,"sortname":"KP","name":"Korea North","phoneCode":850    },
{"country_id":116,"sortname":"KR","name":"Korea South","phoneCode":82    },
{"country_id":117,"sortname":"KW","name":"Kuwait","phoneCode":965    },
{"country_id":118,"sortname":"KG","name":"Kyrgyzstan","phoneCode":996    },
{"country_id":119,"sortname":"LA","name":"Laos","phoneCode":856    },
{"country_id":120,"sortname":"LV","name":"Latvia","phoneCode":371    },
{"country_id":121,"sortname":"LB","name":"Lebanon","phoneCode":961    },
{"country_id":122,"sortname":"LS","name":"Lesotho","phoneCode":266    },
{"country_id":123,"sortname":"LR","name":"Liberia","phoneCode":231    },
{"country_id":124,"sortname":"LY","name":"Libya","phoneCode":218    },
{"country_id":125,"sortname":"LI","name":"Liechtenstein","phoneCode":423    },
{"country_id":126,"sortname":"LT","name":"Lithuania","phoneCode":370    },
{"country_id":127,"sortname":"LU","name":"Luxembourg","phoneCode":352    },
{"country_id":128,"sortname":"MO","name":"Macau S.A.R.","phoneCode":853    },
{"country_id":129,"sortname":"MK","name":"Macedonia","phoneCode":389    },
{"country_id":130,"sortname":"MG","name":"Madagascar","phoneCode":261    },
{"country_id":131,"sortname":"MW","name":"Malawi","phoneCode":265    },
{ "country_id":132,"sortname":"MY","name":"Malaysia","phoneCode":60    },
{ "country_id":133,"sortname":"MV","name":"Maldives","phoneCode":960    },
{  "country_id":134,"sortname":"ML","name":"Mali","phoneCode":223    },
{ "country_id":135,"sortname":"MT","name":"Malta","phoneCode":356    },
{   "country_id":136,"sortname":"XM","name":"Man (Isle of)","phoneCode":44    },
{   "country_id":137,"sortname":"MH","name":"Marshall Islands","phoneCode":692    },
{   "country_id":138,"sortname":"MQ","name":"Martinique","phoneCode":596    },
{   "country_id":139,"sortname":"MR","name":"Mauritania","phoneCode":222    },
{   "country_id":140,"sortname":"MU","name":"Mauritius","phoneCode":230    },
{   "country_id":141,"sortname":"YT","name":"Mayotte","phoneCode":269    },
{   "country_id":142,"sortname":"MX","name":"Mexico","phoneCode":52    },
{   "country_id":143,"sortname":"FM","name":"Micronesia","phoneCode":691    },
{   "country_id":144,"sortname":"MD","name":"Moldova","phoneCode":373    },
{   "country_id":145,"sortname":"MC","name":"Monaco","phoneCode":377    },
{   "country_id":146,"sortname":"MN","name":"Mongolia","phoneCode":976    },
{   "country_id":147,"sortname":"MS","name":"Montserrat","phoneCode":1664    },
{   "country_id":148,"sortname":"MA","name":"Morocco","phoneCode":212    },
{   "country_id":149,"sortname":"MZ","name":"Mozambique","phoneCode":258    },
{   "country_id":150,"sortname":"MM","name":"Myanmar","phoneCode":95    },
{ "country_id":151,"sortname":"NA","name":"Namibia","phoneCode":264    },
{   "country_id":152,"sortname":"NR","name":"Nauru","phoneCode":674    },
{   "country_id":153,"sortname":"NP","name":"Nepal","phoneCode":977    },
{   "country_id":154,"sortname":"AN","name":"Netherlands Antilles","phoneCode":599    },
{   "country_id":155,"sortname":"NL","name":"Netherlands The","phoneCode":31    },
{   "country_id":156,"sortname":"NC","name":"New Caledonia","phoneCode":687    },
{   "country_id":157,"sortname":"NZ","name":"New Zealand","phoneCode":64    },
{   "country_id":158,"sortname":"NI","name":"Nicaragua","phoneCode":505    },
{   "country_id":159,"sortname":"NE","name":"Niger","phoneCode":227    },
{   "country_id":160,"sortname":"NG","name":"Nigeria","phoneCode":234    },
{   "country_id":161,"sortname":"NU","name":"Niue","phoneCode":683    },
{   "country_id":162,"sortname":"NF","name":"Norfolk Island","phoneCode":672    },
{   "country_id":163,"sortname":"MP","name":"Northern Mariana Islands","phoneCode":1670    },
{   "country_id":164,"sortname":"NO","name":"Norway","phoneCode":47    },
{   "country_id":165,"sortname":"OM","name":"Oman","phoneCode":968    },
{   "country_id":166,"sortname":"PK","name":"Pakistan","phoneCode":92    },
{   "country_id":167,"sortname":"PW","name":"Palau","phoneCode":680    },
{   "country_id":168,"sortname":"PS","name":"Palestinian Territory Occupied","phoneCode":970    },
{   "country_id":169,"sortname":"PA","name":"Panama","phoneCode":507    },
{   "country_id":170,"sortname":"PG","name":"Papua new Guinea","phoneCode":675    },
{   "country_id":171,"sortname":"PY","name":"Paraguay","phoneCode":595    },
{   "country_id":172,"sortname":"PE","name":"Peru","phoneCode":51    },
{   "country_id":173,"sortname":"PH","name":"Philippines","phoneCode":63    },
{   "country_id":174,"sortname":"PN","name":"Pitcairn Island","phoneCode":0    },
{   "country_id":175,"sortname":"PL","name":"Poland","phoneCode":48    },
{   "country_id":176,"sortname":"PT","name":"Portugal","phoneCode":351    },
{   "country_id":177,"sortname":"PR","name":"Puerto Rico","phoneCode":1787    },
{   "country_id":178,"sortname":"QA","name":"Qatar","phoneCode":974    },
{   "country_id":179,"sortname":"RE","name":"Reunion","phoneCode":262    },
{   "country_id":180,"sortname":"RO","name":"Romania","phoneCode":40    },
{   "country_id":181,"sortname":"RU","name":"Russia","phoneCode":70    },
{   "country_id":182,"sortname":"RW","name":"Rwanda","phoneCode":250    },
{   "country_id":183,"sortname":"SH","name":"Saint Helena","phoneCode":290    },
{   "country_id":184,"sortname":"KN","name":"Saint Kitts And Nevis","phoneCode":1869    },
{   "country_id":185,"sortname":"LC","name":"Saint Lucia","phoneCode":1758    },
{   "country_id":186,"sortname":"PM","name":"Saint Pierre and Miquelon","phoneCode":508    },
{   "country_id":187,"sortname":"VC","name":"Saint Vincent And The Grenadines","phoneCode":1784    },
{   "country_id":188,"sortname":"WS","name":"Samoa","phoneCode":684    },
{   "country_id":189,"sortname":"SM","name":"San Marino","phoneCode":378    },
{   "country_id":190,"sortname":"ST","name":"Sao Tome and Principe","phoneCode":239    },
{  "country_id":191,"sortname":"SA","name":"Saudi Arabia","phoneCode":966    },
{   "country_id":192,"sortname":"SN","name":"Senegal","phoneCode":221    },
{   "country_id":193,"sortname":"RS","name":"Serbia","phoneCode":381    },
{   "country_id":194,"sortname":"SC","name":"Seychelles","phoneCode":248    },
{   "country_id":195,"sortname":"SL","name":"Sierra Leone","phoneCode":232    },
{   "country_id":196,"sortname":"SG","name":"Singapore","phoneCode":65    },
{   "country_id":197,"sortname":"SK","name":"Slovakia","phoneCode":421    },
{   "country_id":198,"sortname":"SI","name":"Slovenia","phoneCode":386    },
{   "country_id":199,"sortname":"XG","name":"Smaller Territories of the UK","phoneCode":44    },
{   "country_id":200,"sortname":"SB","name":"Solomon Islands","phoneCode":677    },
{   "country_id":201,"sortname":"SO","name":"Somalia","phoneCode":252    },
{  "country_id":202,"sortname":"ZA","name":"South Africa","phoneCode":27    },
{   "country_id":203,"sortname":"GS","name":"South Georgia","phoneCode":0    },
{   "country_id":204,"sortname":"SS","name":"South Sudan","phoneCode":211    },
{   "country_id":205,"sortname":"ES","name":"Spain","phoneCode":34    },
{   "country_id":206,"sortname":"LK","name":"Sri Lanka","phoneCode":94    },
{   "country_id":207,"sortname":"SD","name":"Sudan","phoneCode":249    },
{   "country_id":208,"sortname":"SR","name":"Suriname","phoneCode":597    },
{  "country_id":209,"sortname":"SJ","name":"Svalbard And Jan Mayen Islands","phoneCode":47    },
{   "country_id":210,"sortname":"SZ","name":"Swaziland","phoneCode":268    },
{   "country_id":211,"sortname":"SE","name":"Sweden","phoneCode":46    },
{   "country_id":212,"sortname":"CH","name":"Switzerland","phoneCode":41    },
{   "country_id":213,"sortname":"SY","name":"Syria","phoneCode":963    },
{   "country_id":214,"sortname":"TW","name":"Taiwan","phoneCode":886    },
{   "country_id":215,"sortname":"TJ","name":"Tajikistan","phoneCode":992    },
{   "country_id":216,"sortname":"TZ","name":"Tanzania","phoneCode":255    },
{   "country_id":217,"sortname":"TH","name":"Thailand","phoneCode":66    },
{   "country_id":218,"sortname":"TG","name":"Togo","phoneCode":228    },
{   "country_id":219,"sortname":"TK","name":"Tokelau","phoneCode":690    },
{   "country_id":220,"sortname":"TO","name":"Tonga","phoneCode":676    },
{   "country_id":221,"sortname":"TT","name":"Trincountry_idad And Tobago","phoneCode":1868    },
{   "country_id":222,"sortname":"TN","name":"Tunisia","phoneCode":216    },
{   "country_id":223,"sortname":"TR","name":"Turkey","phoneCode":90    },
{   "country_id":224,"sortname":"TM","name":"Turkmenistan","phoneCode":7370    },
{   "country_id":225,"sortname":"TC","name":"Turks And Caicos Islands","phoneCode":1649    },
{   "country_id":226,"sortname":"TV","name":"Tuvalu","phoneCode":688    },
{   "country_id":227,"sortname":"UG","name":"Uganda","phoneCode":256    },
{   "country_id":228,"sortname":"UA","name":"Ukraine","phoneCode":380    },
{    "country_id":229,"sortname":"AE","name":"United Arab Emirates","phoneCode":971    },
{   "country_id":230,"sortname":"GB","name":"United Kingdom","phoneCode":44    },
{    "country_id":231,"sortname":"US","name":"United States","phoneCode":1    },
{    "country_id":232,"sortname":"UM","name":"United States Minor Outlying Islands","phoneCode":1    },
{    "country_id":233,"sortname":"UY","name":"Uruguay","phoneCode":598    },
{    "country_id":234,"sortname":"UZ","name":"Uzbekistan","phoneCode":998    },
{    "country_id":235,"sortname":"VU","name":"Vanuatu","phoneCode":678    },
{    "country_id":236,"sortname":"VA","name":"Vatican City State (Holy See)","phoneCode":39    },
{    "country_id":237,"sortname":"VE","name":"Venezuela","phoneCode":58    },
{    "country_id":238,"sortname":"VN","name":"Vietnam","phoneCode":84    },
{    "country_id":239,"sortname":"VG","name":"Virgin Islands (British)","phoneCode":1284    },
{    "country_id":240,"sortname":"VI","name":"Virgin Islands (US)","phoneCode":1340    },
{    "country_id":241,"sortname":"WF","name":"Wallis And Futuna Islands","phoneCode":681    },
{    "country_id":242,"sortname":"EH","name":"Western Sahara","phoneCode":212    },
{    "country_id":243,"sortname":"YE","name":"Yemen","phoneCode":967    },
{    "country_id":244,"sortname":"YU","name":"Yugoslavia","phoneCode":38    },
{    "country_id":245,"sortname":"ZM","name":"Zambia","phoneCode":260    }

    ]

    for (var i=0; i<body.length; i++) {
        let countries = new Countries({ country_id: body[i].country_id, sortname: body[i].sortname, name:body[i].name,phoneCode:body[i].phoneCode });
   await countries.save(); 
   console.log("Adding Countries")
  }
   return res.status(200).send({success:1, message: 'Record inserted successfully.', error:0, data:body.length});


})
module.exports=router